name = 'Typescript'
license = 'MIT'
licenselink = 'https://github.com/lubeso/hugo-theme-typescript/LICENSE'
description = 'Enables TypeScript.'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/lubeso/hugo-theme-typescript'

# If the theme has a single author
[author]
  name = 'Luis Becerra Solis'
  homepage = 'https://www.lubeso.dev'
